### ISSUE TITLE
Could use $'' escaping instead of keycodes

### ISSUE THREAD

**Issue by matthijskooijman** [gcb/AdbPaste#6]
This script could be improved to support all ASCII characters, including those that do not have any keycode associated to them, by using the `$''` string literal support in the Android terminal. Essentiall it means to run something like `adb shell input text "\$'\x61'"` to send the letter 'a', where the Android shell would interpret the \x61 and pass 'a' to the input command. Here's an example in bash that shows this works:

https://android.stackexchange.com/a/176590/223695

**Comment by koroshiya** [comment]
I've just taken a stab at this on: https://github.com/gcb/AdbPaste/tree/Issue6

All seems to be working on Linux. Haven't tested on Windows, though I don't see why it would be any different.

Currently doesn't implement --fast (just uses it by default).

**Comment by matthijskooijman** [comment]
I just ran your code for a quick test drive, it works as expected here (Linux + Fairphone 2).

Two additional suggestions, though:
 - You currently use os.system, which requires further quoting and possibly escaping of the arguments because the command is passed through the shell on the host system. I would suggest using the subprocess module, where you can pass a list containing the command and each argument separately, which does not need the shell to split arguments. This should limit potential problems with the shell interpreting things you didn't want to be interpreted.
 - The tool currently allows sending from the commandline, or from a file. How about, if neither a file or a text are passed, asking for a text to send on the commandline? My usecase is sending passwords to my device. Storing them in a file to pass to AdbPaste is cumbersome, but I also do not want to pass them on the commandline (process arguments are not completely private in a multi-user system, they might end up in my shell history if I'm not careful, etc.). Asking for the text on stdin would solve this and prevent the password from being stored anywhere. As a workaround I can now pass `--file /dev/stdin` and then paste into stdin + ^D for EOF, but it might be interesting to make this easier.
